# Generated by Django 4.1.4 on 2022-12-08 12:54

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("app", "0003_alter_exercise_description"),
    ]

    operations = [
        migrations.RenameModel(
            old_name="BodyShape",
            new_name="Shape",
        ),
        migrations.AlterModelOptions(
            name="day",
            options={"ordering": ["day"]},
        ),
        migrations.AlterModelOptions(
            name="exercise",
            options={"ordering": ["info"]},
        ),
        migrations.AlterModelOptions(
            name="muscle",
            options={"ordering": ["title"]},
        ),
        migrations.AlterModelOptions(
            name="shape",
            options={"ordering": ["id"]},
        ),
        migrations.AlterModelOptions(
            name="training",
            options={"ordering": ["day"]},
        ),
    ]
